#!/usr/bin/env python3
"""
Guía para obtener la URL correcta de Supabase
"""

print("🔍 PASOS PARA OBTENER LA URL CORRECTA DE SUPABASE:")
print("="*60)
print()
print("1. Ve a tu dashboard de Supabase: https://supabase.com/dashboard")
print("2. Selecciona tu proyecto")
print("3. Ve a Settings → Database")
print("4. En la sección 'Connection String', busca:")
print("   - URI (recomendado para aplicaciones)")
print("   - Connection Pooling")
print()
print("5. COPIA LA URL COMPLETA que aparece ahí")
print("   Debería verse similar a una de estas:")
print()
print("   Opción A (Direct):")
print("   postgresql://postgres:[PASSWORD]@db.PROJECT_ID.supabase.co:5432/postgres")
print()
print("   Opción B (Pooled):")
print("   postgresql://postgres.PROJECT_ID:[PASSWORD]@aws-0-REGION.pooler.supabase.com:6543/postgres")
print()
print("6. IMPORTANTE: Asegúrate de que:")
print("   - El hostname sea exactamente como aparece en tu dashboard")
print("   - El puerto sea el correcto (5432 o 6543)")
print("   - Tu contraseña esté correcta")
print()
print("7. Una vez que tengas la URL correcta, actualízala en:")
print("   - Variable de entorno DATABASE_URL")
print("   - O directamente en tu código para probar")
print()
print("="*60)
print("💡 POSIBLES PROBLEMAS:")
print()
print("1. PROYECTO PAUSADO:")
print("   - Ve a tu dashboard y verifica que el proyecto esté activo")
print("   - Si está pausado, reactívalo")
print()
print("2. CONTRASEÑA INCORRECTA:")
print("   - Ve a Settings → Database → Reset database password")
print("   - Genera una nueva contraseña")
print()
print("3. HOSTNAME INCORRECTO:")
print("   - Copia exactamente el hostname de tu dashboard")
print("   - No uses URLs de ejemplos o documentación")
print()
print("4. FIREWALL/NETWORK:")
print("   - Verifica que tu conexión permita conexiones a Supabase")
print("   - Intenta desde otra red si es posible")
print()
print("="*60)
print("🧪 PARA PROBAR LA CONEXIÓN:")
print()
print("Una vez que tengas la URL correcta, ejecuta:")
print("python test_supabase_connection.py")
print()
print("="*60)
