services:
  - type: web
    name: compraventa-valle-uco
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SESSION_SECRET
        value: valle-uco-marketplace-secret-key-2024
      - key: ADMIN_PASSWORD
        value: AdminValleUco2024
      - key: PYTHON_VERSION
        value: 3.11.6

databases:
  - name: compraventa-valle-uco-db
    databaseName: marketplace
    user: marketplace_user
